version: "3.8"

services:
  db:
    image: postgres:15
    container_name: snapify-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snapify
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapify-backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  pgdata:
